### PR TITLE
Add Distributive instances

### PR DESCRIPTION
**Pull request by catostrophe**
This is to address issue #28.

### CODE REVIEW

**Comment by julien-truffaut** [comment]
nice I didn't know about `Distributive`! 👍

**Comment by catostrophe** [comment]
Yes, and it's not far fetched. I needed it for Dual in my project to reduce boilerplate and had to implement one myself. I wish newts already had it.

**Comment by julien-truffaut** [comment]
@catostrophe do you want me to cut a release with this change?

**Comment by catostrophe** [comment]
Would be great

**Comment by julien-truffaut** [comment]
np, I released 0.3.2

**Pull request merged**
