### PR TITLE
Update to Cats 1.0.0-MF.

### PR DESCRIPTION
**Pull request by sellout**

### CODE REVIEW

**Comment by sellout** [comment]
This currently errors on some Show tests, and I’m not sure why.

**Comment by julien-truffaut** [comment]
```
[info] newts.LastTest *** ABORTED ***
[info]   java.lang.ClassFormatError: Duplicate method name&signature in class file newts/Last$$anon$3
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
```

**Comment by julien-truffaut** [comment]
I don't understand why we got this failure with your changes ...

**Comment by sellout** [comment]
Yeah, I get it locally, too – I’m guessing it’s due to some upstream change in Cats.

The rest of the stack trace points to the `Show` instances of those classes that error. But even using a constant string as the result of `show` results in the same error. However other classes have show instances that are also tested but don’t fail. I don’t know what makes the erroring cases special.

**Comment by julien-truffaut** [comment]
I wonder if we would have the same problem without `AnyVal`

**Pull request closed without merging**
